import a2_pgm8 as q
q.enque(10)
q.enque(20)
q.enque(30)
q.enque(50)
print(q.s.data)
q.deque()
q.deque()
q.deque()
q.enque(10)
q.enque(20)
print(q.s.data)
print(q.length())
print(q.front())